services:
  caddy:
    image: react-website
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    image: dotnet-backend
    build:
      context: ./restaurant-api
      dockerfile: Dockerfile.Backend
    container_name: backend-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DATABASE_CONNECTION=Server=postgres-service;Database=${DATABASE};UserId=${USER_ID};Password=${PASSWORD}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_ID}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_ID} -d ${DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - ./restaurant-api:/app
    working_dir: /app
    command: ["dotnet", "ef", "database", "update", "--context", "RestaurantDb"]
    environment:
      - DATABASE_CONNECTION=Server=postgres-service;Database=${DATABASE};UserId=${USER_ID};Password=${PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
